# CMake generated Testfile for 
# Source directory: /projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave
# Build directory: /projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ccb_stave_geometry_smoke "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--macro" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/macros/geometry_check.mac" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/geometry_smoke.root")
set_tests_properties(ccb_stave_geometry_smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "GEOMETRY_SELFCHECK_FAIL;Overlap is detected;G4Exception.*Fatal" PASS_REGULAR_EXPRESSION "GEOMETRY_SELFCHECK_PASS" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;59;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_proton_smoke "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "5" "--seed" "1" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/proton_smoke.root")
set_tests_properties(ccb_stave_proton_smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "CCB_STAVE_END" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;71;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_wls_profile "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "5" "--seed" "1" "--wls-time-profile" "exponential" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/wls_profile.root")
set_tests_properties(ccb_stave_wls_profile PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "wls_time_profile=exponential" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;83;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_gdml_export "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--dump-gdml" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/exported.gdml" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/gdml_export.root" "--nevents" "1")
set_tests_properties(ccb_stave_gdml_export PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "CCB_GDML_WROTE" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;96;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_gpu_optical_capture "/usr/bin/cmake" "-E" "env" "CCB_GPU_OPTICAL=1" "ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "1" "--seed" "1" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/gpu_optical.root" "--optical-out" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical_gpu_ctest")
set_tests_properties(ccb_stave_gpu_optical_capture PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "CCB_GPU_PHOTONS" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;109;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_geometry_report_python "/usr/bin/python3" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/tests/check_geometry_report.py" "--exe" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--macro" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/macros/geometry_check.mac")
set_tests_properties(ccb_stave_geometry_report_python PROPERTIES  _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;122;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_birks_visible_regression "/usr/bin/python3" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/tests/test_birks_visible_regression.py" "--exe" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--work-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/birks_regression")
set_tests_properties(ccb_stave_birks_visible_regression PROPERTIES  FAIL_REGULAR_EXPRESSION "defect 2 has regressed" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;138;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_production_cut_regression "/usr/bin/python3" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/tests/test_production_cut_regression.py" "--exe" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--work-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/production_cut_regression")
set_tests_properties(ccb_stave_production_cut_regression PROPERTIES  FAIL_REGULAR_EXPRESSION "issue #1089 may have regressed" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;158;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_far_end_modes "/usr/bin/python3" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/tests/test_far_end_modes.py" "--exe" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--macro" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/macros/geometry_check.mac" "--work-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/far_end_modes")
set_tests_properties(ccb_stave_far_end_modes PROPERTIES  FAIL_REGULAR_EXPRESSION "SOME FAR-END MODES FAILED" TIMEOUT "600" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;174;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_sipm_arrivals "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "5" "--seed" "1" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/sipm_arrivals.root")
set_tests_properties(ccb_stave_sipm_arrivals PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "SIPM_ARRIVALS.*total=[1-9]" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;188;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_sipm_adc "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "5" "--seed" "1" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/sipm_adc.root")
set_tests_properties(ccb_stave_sipm_adc PROPERTIES  FAIL_REGULAR_EXPRESSION "G4Exception.*Fatal;segmentation" PASS_REGULAR_EXPRESSION "SIPM_ADC.*readout=[1-9]" TIMEOUT "300" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;199;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_sipm_env_fail_closed "/usr/bin/python3" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/tests/test_sipm_env_fail_closed.py" "--exe" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical")
set_tests_properties(ccb_stave_sipm_env_fail_closed PROPERTIES  PASS_REGULAR_EXPRESSION "SIPM_ENV_FAIL_CLOSED_PASS" TIMEOUT "300" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;212;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
add_test(ccb_stave_sipm_n_cells_nonsquare_fail "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/ccb_stave_sim" "--particle" "proton" "--energy" "100" "--nevents" "1" "--seed" "1" "--sipm-n-cells" "1800" "--optical-dir" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/optical" "--output" "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/build_lane01/sipm_nonsquare.root")
set_tests_properties(ccb_stave_sipm_n_cells_nonsquare_fail PROPERTIES  TIMEOUT "120" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;224;add_test;/projects/hep/fs10/shared/nnbar/billy/ccb-wt-lane01/geant4/single_stave/CMakeLists.txt;0;")
subdirs("sipm")
subdirs("opticks")
