#!/usr/bin/env bash
# run_sensitivity_campaign.sh — orchestrate the SiPM one-knob sensitivity sweep.
#
# Generates the per-knob points CSVs into the campaign output directory, freezes
# source intent plus an independently content-bound ccb_stave_sim build receipt,
# submits one Slurm array per knob, and records every job id. Run the analyzer
# afterwards with `--analyze` (waits for all jobs first) or by hand once jobs drain.
#
# All sizing knobs are env-overridable (no magic numbers):
#   CCB_CAMPASSIGN_NEVENTS      events per point        (default 60)
#   CCB_CAMPASSIGN_CONCURRENCY  max parallel array tasks (default 8)
#   CCB_CAMPASSIGN_TIME         wall time per task HH:MM:SS (default 00:25:00)
#   CCB_CAMPASSIGN_BASE_CLI     common beam CLI          (see generate_points.py)
#   CCB_CAMPASSIGN_KNOBS        space-list of knobs      (default: all)
#   CCB_CAMPASSIGN_OUTDIR       output root              (required; outside repo)
#   CCB_CAMPASSIGN_BUILD        build dir with ccb_stave_sim + build receipt (required)
#
# Authorising builds must be configured with -DCCB_AUTHORISING_BUILD_RECEIPT=ON.
#
# Usage:
#   CCB_CAMPASSIGN_BUILD=.../build CCB_CAMPASSIGN_OUTDIR=.../ccb-runs/sipm-p2-001 \
#     bash run_sensitivity_campaign.sh            # submit only
#   ... CCB_CAMPASSIGN_ANALYZE=1 ...              # submit, wait, analyze
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd -P)"
GRID_SOURCE="${HERE}/grids"
MANIFEST_TOOL="${REPO_ROOT}/scripts/single_stave/sipm_campaign_manifest.py"
BUILD_RECEIPT_TOOL="${REPO_ROOT}/scripts/single_stave/sipm_build_receipt.py"

BUILD="${CCB_CAMPASSIGN_BUILD:?set CCB_CAMPASSIGN_BUILD to the single_stave build dir}"
OUTDIR="${CCB_CAMPASSIGN_OUTDIR:?set CCB_CAMPASSIGN_OUTDIR}"
NEVENTS="${CCB_CAMPASSIGN_NEVENTS:-60}"
CONCURRENCY="${CCB_CAMPASSIGN_CONCURRENCY:-8}"
TIME="${CCB_CAMPASSIGN_TIME:-00:25:00}"
KNOBS="${CCB_CAMPASSIGN_KNOBS:-}"
BASE_CLI="${CCB_CAMPASSIGN_BASE_CLI:---particle proton --energy 100 --hit-x 0 --hit-y 0 --theta 0 --phi 0}"

export CCB_CAMPASSIGN_NEVENTS="$NEVENTS"
export CCB_CAMPASSIGN_BASE_CLI="$BASE_CLI"

mkdir -p "$OUTDIR"
OUTDIR="$(cd "$OUTDIR" && pwd -P)"
case "${OUTDIR}/" in
  "${REPO_ROOT}/"*)
    echo "fatal: CCB_CAMPASSIGN_OUTDIR must be outside the source repository" >&2
    exit 3
    ;;
esac
CAMPAIGN_GRIDS="${OUTDIR}/grids"
mkdir -p "$CAMPAIGN_GRIDS"

EXE="${BUILD}/ccb_stave_sim"
SOURCE_BUILD_RECEIPT="${BUILD}/ccb_stave_sim.build.json"
SOURCE_BUILD_DIGEST_FILE="${BUILD}/ccb_stave_sim.build.sha256"
if [[ ! -f "$EXE" || ! -f "$SOURCE_BUILD_RECEIPT" || ! -f "$SOURCE_BUILD_DIGEST_FILE" ]]; then
  echo "fatal: authorising campaign requires ccb_stave_sim plus ccb_stave_sim.build.{json,sha256}" >&2
  echo "       rebuild with -DCCB_AUTHORISING_BUILD_RECEIPT=ON" >&2
  exit 3
fi
SOURCE_BUILD_SHA256="$(tr -d '[:space:]' < "$SOURCE_BUILD_DIGEST_FILE")"

echo "== SiPM sensitivity campaign (SIPM-P2-001) =="
echo "   build : $BUILD"
echo "   out   : $OUTDIR"
echo "   grids : $CAMPAIGN_GRIDS"
echo "   ev/pt : $NEVENTS   concurrency: $CONCURRENCY   time/task: $TIME"
echo "   base  : $BASE_CLI"

# 1) Generate campaign-specific per-knob grids from the committed generator.
# The generated bytes are mutable campaign artifacts, not source files. They
# therefore live outside the repository and are content-bound by the manifest.
python3 "${GRID_SOURCE}/generate_points.py" --outdir "$CAMPAIGN_GRIDS" \
  ${KNOBS:+--knobs $KNOBS}

# 2) Freeze campaign intent from exact committed repository source plus the
# generated campaign-grid bytes. The creator fails closed when the repository
# working tree is dirty; campaign outputs remain outside that source tree.
MANIFEST="${OUTDIR}/campaign_intent.json"
MANIFEST_DIGEST="${OUTDIR}/campaign_intent.sha256"
manifest_args=(
  create
  --repo-root "$REPO_ROOT"
  --grids-dir "$CAMPAIGN_GRIDS"
  --manifest "$MANIFEST"
  --digest-file "$MANIFEST_DIGEST"
  --base-cli "$BASE_CLI"
  --nevents "$NEVENTS"
)
if [[ -n "$KNOBS" ]]; then
  read -r -a selected_knobs <<< "$KNOBS"
  manifest_args+=(--knobs "${selected_knobs[@]}")
fi
EXPECTED_CORE_SHA="$(python3 "$MANIFEST_TOOL" "${manifest_args[@]}")"
MANIFEST_SHA256="$(tr -d '[:space:]' < "$MANIFEST_DIGEST")"
# Independent verify proves source binding and that live runtime intent equals
# the newly frozen base CLI, event count and single-thread contract.
VERIFY_CORE_SHA="$(python3 "$MANIFEST_TOOL" verify \
  --repo-root "$REPO_ROOT" --manifest "$MANIFEST" \
  --expected-sha256 "$MANIFEST_SHA256" \
  --base-cli "$BASE_CLI" --nevents "$NEVENTS" --threads 1)"
if [[ "$VERIFY_CORE_SHA" != "$EXPECTED_CORE_SHA" ]]; then
  echo "fatal: campaign manifest core mismatch after create" >&2
  exit 3
fi

echo "   intent: $MANIFEST"
echo "   intent sha256: $MANIFEST_SHA256"
echo "   expected core: $EXPECTED_CORE_SHA (superproject gitlink)"

# 3) Freeze the exact build receipt into campaign-owned immutable bytes. The
# receipt verifier requires build source/root/core identity to equal campaign
# source intent and re-hashes the executable, CMake cache, compiler/CMake tools
# and Geant4 package sentinel before accepting the copy.
BUILD_RECEIPT="${OUTDIR}/build_receipt.json"
BUILD_RECEIPT_DIGEST="${OUTDIR}/build_receipt.sha256"
FROZEN_BUILD_SHA256="$(python3 "$BUILD_RECEIPT_TOOL" freeze \
  --receipt "$SOURCE_BUILD_RECEIPT" \
  --expected-sha256 "$SOURCE_BUILD_SHA256" \
  --executable "$EXE" \
  --campaign-manifest "$MANIFEST" \
  --campaign-sha256 "$MANIFEST_SHA256" \
  --repo-root "$REPO_ROOT" \
  --output "$BUILD_RECEIPT" \
  --digest-file "$BUILD_RECEIPT_DIGEST")"
if [[ "$FROZEN_BUILD_SHA256" != "$SOURCE_BUILD_SHA256" ]]; then
  echo "fatal: frozen build receipt digest mismatch" >&2
  exit 3
fi
echo "   build receipt: $BUILD_RECEIPT"
echo "   build receipt sha256: $FROZEN_BUILD_SHA256"

# 4) Submit one array per knob. Both manifest and build-receipt digests are
# copied into every job argv so post-submission substitution fails closed.
JOBIDS_FILE="${OUTDIR}/submitted_job_ids.txt"
: > "$JOBIDS_FILE"

shopt -s nullglob
submitted=0
for csv in "$CAMPAIGN_GRIDS"/points_*.csv; do
  knob="$(basename "$csv" .csv | sed 's/^points_//')"
  if [[ -n "$KNOBS" ]]; then
    case " $KNOBS " in *" $knob "*) ;; *) continue;; esac
  fi
  ndata=$(grep -vE '^\s*(#|$)' "$csv" | grep -vc '^label,')
  if (( ndata == 0 )); then echo "  skip $knob (no points)"; continue; fi
  last=$((ndata - 1))
  echo "  submit $knob : $ndata points  (array 0-${last}%${CONCURRENCY})"
  jid=$(sbatch --array=0-${last}%${CONCURRENCY} --time="$TIME" \
        --account="${CCB_CAMPASSIGN_ACCOUNT:-hep2023-1-3}" \
        --partition="${CCB_CAMPASSIGN_PARTITION:-hep}" \
        "${HERE}/submit_systematic.sh" "$BUILD" "$knob" "$csv" "$OUTDIR" \
        "$MANIFEST" "$MANIFEST_SHA256" "$BUILD_RECEIPT" "$FROZEN_BUILD_SHA256" \
        | awk '{print $NF}')
  echo "$knob $jid" >> "$JOBIDS_FILE"
  submitted=$((submitted+1))
done
echo "submitted $submitted knob arrays; ids in ${JOBIDS_FILE}"
cat "$JOBIDS_FILE"

# 5) Optionally wait for all to finish, then analyze. The expected core and the
# execution-intent check are re-derived from the frozen manifest.
if [[ "${CCB_CAMPASSIGN_ANALYZE:-0}" == "1" ]]; then
  echo "== waiting for all jobs to drain =="
  while true; do
    pending=0
    while read -r knob jid; do
      [[ -z "$jid" ]] && continue
      state=$(sacct -j "$jid" --format=State --noheader -n 2>/dev/null | \
              awk '{print $1}' | sort -u)
      if echo "$state" | grep -qE 'PENDING|RUNNING|REQUEUE'; then
        pending=$((pending+1))
      fi
    done < "$JOBIDS_FILE"
    if (( pending == 0 )); then break; fi
    echo "  $(date -Is) $pending array(s) still active; sleeping 60s"
    sleep 60
  done
  echo "== running analyzer =="
  export MPLCONFIGDIR="${MPLCONFIGDIR:-/projects/hep/fs10/shared/nnbar/billy/.mplcache}"
  PY="${CCB_CAMPASSIGN_PY:-python3}"
  EXPECTED_CORE_SHA="$("$PY" "$MANIFEST_TOOL" verify \
    --repo-root "$REPO_ROOT" --manifest "$MANIFEST" \
    --expected-sha256 "$MANIFEST_SHA256" \
    --base-cli "$BASE_CLI" --nevents "$NEVENTS" --threads 1)"
  "$PY" "${REPO_ROOT}/scripts/single_stave/sipm_sensitivity.py" "$OUTDIR" \
       --grids-dir "$CAMPAIGN_GRIDS" --expected-core-sha "$EXPECTED_CORE_SHA"
fi
echo "campaign submission complete."
