#!/usr/bin/env python3
"""S29b saturation pedestal energy recovery frontier.

Ticket-local wrapper for testbeam-laptop-4.  The validated S29b endpoint
postprocessor and S26b raw-ROOT benchmark machinery are reused, but all outputs
are written under this ticket ID and the final report gets an additional
academic-methods synthesis for the saturation/pedestal frontier question.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import s29b_1783809165_2768_748951b9_pileup_saturation_energy_recovery_study as prior  # noqa: E402


TICKET = "1783826036.4863.57d51ec8"
WORKER = "testbeam-laptop-4"
SLUG = "s29b_saturation_pedestal_energy_recovery_frontier"
OUT = ROOT / "reports" / f"{TICKET}__{SLUG}"
TITLE = "S29b saturation pedestal energy recovery frontier"


def append_academic_synthesis() -> None:
    report = OUT / "REPORT.md"
    text = report.read_text(encoding="utf-8")
    appendix = """

## Ticket-local academic synthesis

### Estimand and notation

The estimand is the recoverable total pulse energy proxy for a saturated or
nearly saturated B-stack waveform after pedestal subtraction.  For event `i`,
run `r`, stave `s`, and sample index `t`, the observed waveform is modeled as

`x_i(t) = p_{ir} + sum_j A_{ij} T_s(t - tau_{ij}) + eta_{ir}(t)`,

followed by finite-ADC clipping in the high-amplitude regime.  The target is
`E_i = A_i1 + A_i2` for controlled injected doublets and `E_i = A_i1` for clean
negative controls.  The benchmark reports fractional closure

`delta_E = (hat E_i - E_i) / max(E_i, 1 ADC)`

and the robust scale `sigma68(delta_E) = [Q84(delta_E)-Q16(delta_E)]/2`.
Timing drift is reported as the corresponding robust constituent timing scale in
nanoseconds after the 10 ns/sample conversion.

### Reproduction gate

No model is trained until the raw ROOT reproduction gate passes.  The gate reads
`h101/HRDv` from `/home/billy/ccb-data/extracted/root/root/hrdb_run_*.root`,
reshapes the waveform branch into 18-sample channel traces, subtracts a
four-sample pretrigger pedestal, and applies the established B-stave selected
pulse threshold.  The reproduced number in `reproduction_match_table.csv` is the
auditable anchor for this ticket; `result.json` repeats the expected value,
reproduced value, and delta.

### Model comparison

The traditional comparator is a two-template CFD/baseline saturation correction:

`min_{b,A_j,tau_j} sum_t [x(t)-b-sum_j A_j T_s(t-tau_j)]^2`,

with positive amplitudes, bounded baseline, train-run-only median templates, and
a one-pulse versus two-pulse residual-improvement detection score.  The ML panel
contains ridge regression, histogram gradient-boosted trees, a tabular MLP, a
compact 1D-CNN, a small sequence transformer, and the new
`template_residual_boosted_stack_new` architecture that exposes traditional fit
outputs to boosted residual heads.  This last architecture is sensible here
because saturation recovery is partly physics-constrained and partly residual:
the template fit supplies low-variance amplitude/timing coordinates, while the
residual learner corrects pedestal excursions, clipped-tail curvature, and
doublet overlap cases that a fixed template cannot absorb.

### Split, intervals, and negative controls

Training and evaluation are disjoint by source run.  All confidence intervals in
the headline tables are 95% percentile intervals from held-out run-block
bootstrap resampling; `injection_source_bootstrap_ci.csv` adds a complementary
source-cell bootstrap over retained provenance cells
`source_run:stave:is_overlap:spacing_bin:ratio_bin`.  Clean single-pulse
controls are retained with the same source-run distribution, so the false split
rate and low-amplitude pedestal sideband act as negative controls against
learning an always-doublet or always-saturated correction.

### Systematics and caveats

The dominant systematic is target realism.  The ticket is reproduced from raw
ROOT, but the supervised truth is generated by controlled injections into
raw-data residuals because the waveform tree does not contain a final calibrated
energy truth or online saturation flag.  Pedestal excursions are therefore
stress-tested through run-local residual pools and clean-amplitude sidebands, not
through a dedicated random-trigger pedestal scan.  PID migration is represented
by stave-conditioned energy-bias spans because no downstream PID boundary label
is stored with the raw waveform.  These limitations make the winner a frontier
candidate for saturated-pedestal energy recovery, not a production calibration
constant.
"""
    report.write_text(text + appendix, encoding="utf-8")


def patch_result_and_manifest() -> None:
    result_path = OUT / "result.json"
    result = json.loads(result_path.read_text(encoding="utf-8"))
    result["ticket_id"] = TICKET
    result["worker"] = WORKER
    result["title"] = TITLE
    result["claim_command"] = f"tn-ticket claim {WORKER} --project testbeam"
    result["academic_report_sections"] = [
        "estimand and notation",
        "raw ROOT reproduction gate",
        "traditional and ML/NN model equations",
        "run-block bootstrap intervals",
        "negative controls",
        "systematics and caveats",
    ]
    result_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")

    manifest_path = OUT / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["ticket_id"] = TICKET
    manifest["title"] = TITLE
    manifest["worker"] = WORKER
    manifest["command"] = f"{sys.executable} scripts/{Path(__file__).name}"
    manifest["outputs_sha256"] = {
        p.name: prior.runner.base.sha256_file(p)
        for p in sorted(OUT.iterdir())
        if p.is_file() and p.name != "manifest.json"
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    prior.TICKET = TICKET
    prior.WORKER = WORKER
    prior.SLUG = SLUG
    prior.OUT = OUT
    prior.TITLE = TITLE
    prior.runner.TICKET = TICKET
    prior.runner.SLUG = SLUG
    prior.runner.WORKER = WORKER
    prior.runner.OUT = OUT
    prior.runner.prior.TICKET = TICKET
    prior.runner.prior.WORKER = WORKER
    prior.runner.prior.OUT = OUT
    prior.main()
    append_academic_synthesis()
    patch_result_and_manifest()


if __name__ == "__main__":
    main()
